import Config

database_url = System.get_env("DATABASE_URL")

http_ip =
  case System.get_env("PHX_HTTP_IP") do
    "0.0.0.0" -> {0, 0, 0, 0}
    "127.0.0.1" -> {127, 0, 0, 1}
    _ -> {127, 0, 0, 1}
  end

# Configure your database
if is_binary(database_url) and database_url != "" do
  config :adventure_time_api, AdventureTimeApi.Repo,
    url: database_url,
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
else
  config :adventure_time_api, AdventureTimeApi.Repo,
    username: "postgres",
    password: "postgres",
    hostname: "127.0.0.1",
    port: 5434,
    database: "adventure_time_tcg",
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :adventure_time_api, AdventureTimeApiWeb.Endpoint,
  http: [ip: http_ip, port: String.to_integer(System.get_env("PHX_PORT") || "4200")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "lQJ4uCP25x0E4La0CRbTcvN2xanEW8qIM08HNVSM0suVDFy2R6Ow44QWJWm4BrY0",
  watchers: []

config :adventure_time_api, AdventureTimeApi.Auth,
  access_token_secret:
    System.get_env("ACCESS_TOKEN_SECRET") ||
      "dev-access-token-secret-please-change-1234567890",
  refresh_token_secret:
    System.get_env("REFRESH_TOKEN_SECRET") ||
      "dev-refresh-token-secret-please-change-1234567890",
  google_client_ids:
    [
      System.get_env("AUTH_GOOGLE_ID"),
      System.get_env("GOOGLE_IOS_CLIENT_ID"),
      System.get_env("GOOGLE_ANDROID_CLIENT_ID")
    ]
    |> Enum.reject(&is_nil/1)
    |> Enum.reject(&(&1 == "")),
  apple_client_ids:
    [
      System.get_env("APPLE_BUNDLE_ID") || "love.leaetzak.adventuretime",
      System.get_env("IOS_BUNDLE_IDENTIFIER")
    ]
    |> Enum.reject(&is_nil/1)
    |> Enum.reject(&(&1 == ""))

config :adventure_time_api, AdventureTimeApi.Accounts,
  verification_secret:
    System.get_env("EMAIL_VERIFICATION_SECRET") ||
      "dev-email-verification-secret-please-change-1234567890",
  expose_dev_code: System.get_env("AUTH_EMAIL_EXPOSE_DEV_CODE") == "true"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :adventure_time_api, AdventureTimeApiWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/gettext/.*(po)$",
      ~r"lib/adventure_time_api_web/(?:controllers|router)/?.*\.ex$",
      ~r"lib/adventure_time_api/(?:accounts|catalog|inventory)/?.*\.ex$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
