/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        fg: 'var(--color-fg)',
        surface: 'var(--color-surface)',
        surfaceMuted: 'var(--color-surface-muted)',
        fgMuted: 'var(--color-fg-muted)',
        muted: 'var(--color-muted)',
        pinkLight: 'var(--color-pink-light)',
        pinkMedium: 'var(--color-pink-medium)',
        pinkDark: 'var(--color-pink-dark)',
        yellowLight: 'var(--color-yellow-light)',
        yellowMedium: 'var(--color-yellow-medium)',
        mint: 'var(--color-mint)',
        lavender: 'var(--color-lavender)',
        primary: 'var(--color-primary)',
        primaryDark: 'var(--color-primary-dark)',
        primaryText: 'var(--color-primary-text)',
        primaryStrong: 'var(--color-primary-strong)',
        primaryBorder: 'var(--color-primary-border)',
        primaryBg: 'var(--color-primary-bg)',
        primaryTint: 'var(--color-primary-tint)',
        secondary: 'var(--color-secondary)',
        secondaryDark: 'var(--color-secondary-dark)',
        secondaryText: 'var(--color-secondary-text)',
        secondaryTint: 'var(--color-secondary-tint)',
        secondaryBorder: 'var(--color-secondary-border)',
        accent: 'var(--color-accent)',
        accentDark: 'var(--color-accent-dark)',
        accentText: 'var(--color-accent-text)',
        accentStrong: 'var(--color-accent-strong)',
        accentTint: 'var(--color-accent-tint)',
        accentBorder: 'var(--color-accent-border)',
        success: 'var(--color-success)',
        successDark: 'var(--color-success-dark)',
        successText: 'var(--color-success-text)',
        successTint: 'var(--color-success-tint)',
        successBorder: 'var(--color-success-border)',
        danger: 'var(--color-danger)',
        dangerDark: 'var(--color-danger-dark)',
        dangerText: 'var(--color-danger-text)',
        dangerTint: 'var(--color-danger-tint)',
        dangerBorder: 'var(--color-danger-border)',
        info: 'var(--color-info)',
        infoDark: 'var(--color-info-dark)',
        infoText: 'var(--color-info-text)',
        infoTint: 'var(--color-info-tint)',
        infoBorder: 'var(--color-info-border)',
      },
      fontFamily: {
        nunito: ["Nunito_400Regular"],
        "nunito-semibold": ["Nunito_600SemiBold"],
        "nunito-bold": ["Nunito_700Bold"],
        "nunito-extrabold": ["Nunito_800ExtraBold"],
      },
    },
  },
  plugins: [],
};
