import { vars } from "nativewind";

export type ThemeName = "candy" | "ice" | "nightosphere";

export function getExpoUIColorScheme(themeName: ThemeName): "light" | "dark" {
  return themeName === "nightosphere" ? "dark" : "light";
}

// ---------------------------------------------------------------------------
// Raw color objects — for LinearGradient, placeholderTextColor, tab bar, etc.
// ---------------------------------------------------------------------------
export const THEME_COLORS: Record<
  ThemeName,
  {
    bg: string;
    fg: string;
    surface: string;
    surfaceMuted: string;
    fgMuted: string;
    muted: string;
    primary: string;
    primaryDark: string;
    primaryText: string;
    primaryStrong: string;
    primaryBorder: string;
    primaryBg: string;
    primaryTint: string;
    secondary: string;
    secondaryDark: string;
    secondaryText: string;
    secondaryTint: string;
    secondaryBorder: string;
    accent: string;
    accentDark: string;
    accentText: string;
    accentStrong: string;
    accentTint: string;
    accentBorder: string;
    success: string;
    successDark: string;
    successText: string;
    successTint: string;
    successBorder: string;
    danger: string;
    dangerDark: string;
    dangerText: string;
    dangerTint: string;
    dangerBorder: string;
    info: string;
    infoDark: string;
    infoText: string;
    infoTint: string;
    infoBorder: string;
  }
> = {
  candy: {
    bg: "#fff0f5",
    fg: "#4a3728",
    surface: "rgba(255,255,255,0.96)",
    surfaceMuted: "rgba(255,255,255,0.9)",
    fgMuted: "#6b7280",
    muted: "#9CA3AF",
    primary: "#F472B6",
    primaryDark: "#EC4899",
    primaryText: "#DB2777",
    primaryStrong: "#BE185D",
    primaryBorder: "#F9A8D4",
    primaryBg: "#FDF2F8",
    primaryTint: "#FCE7F3",
    secondary: "#FDE047",
    secondaryDark: "#FACC15",
    secondaryText: "#894B00",
    secondaryTint: "#FEF9C3",
    secondaryBorder: "#FEF08A",
    accent: "#C084FC",
    accentDark: "#A855F7",
    accentText: "#9333EA",
    accentStrong: "#7C3AED",
    accentTint: "#F3E8FF",
    accentBorder: "#E9D5FF",
    success: "#2DD4BF",
    successDark: "#14B8A6",
    successText: "#005F5A",
    successTint: "#CCFBF1",
    successBorder: "#96F7E4",
    danger: "#FB7185",
    dangerDark: "#F43F5E",
    dangerText: "#A50036",
    dangerTint: "#FFE4E6",
    dangerBorder: "#FECDD3",
    info: "#818CF8",
    infoDark: "#6366F1",
    infoText: "#4F46E5",
    infoTint: "#E0E7FF",
    infoBorder: "#C7D2FE",
  },
  ice: {
    bg: "#F0F7FF",
    fg: "#1F2937",
    surface: "rgba(255,255,255,0.98)",
    surfaceMuted: "rgba(240,247,255,0.95)",
    fgMuted: "#6B7280",
    muted: "#94A3B8",
    primary: "#60A5FA",
    primaryDark: "#3B82F6",
    primaryText: "#1D4ED8",
    primaryStrong: "#1E40AF",
    primaryBorder: "#BFDBFE",
    primaryBg: "#EFF6FF",
    primaryTint: "#DBEAFE",
    secondary: "#67E8F9",
    secondaryDark: "#22D3EE",
    secondaryText: "#0E7490",
    secondaryTint: "#CFFAFE",
    secondaryBorder: "#A5F3FC",
    accent: "#818CF8",
    accentDark: "#6366F1",
    accentText: "#4338CA",
    accentStrong: "#3730A3",
    accentTint: "#E0E7FF",
    accentBorder: "#C7D2FE",
    success: "#34D399",
    successDark: "#10B981",
    successText: "#065F46",
    successTint: "#D1FAE5",
    successBorder: "#6EE7B7",
    danger: "#F87171",
    dangerDark: "#EF4444",
    dangerText: "#B91C1C",
    dangerTint: "#FEE2E2",
    dangerBorder: "#FECACA",
    info: "#60A5FA",
    infoDark: "#3B82F6",
    infoText: "#1D4ED8",
    infoTint: "#DBEAFE",
    infoBorder: "#BFDBFE",
  },
  nightosphere: {
    bg: "#0D0010",
    fg: "#F0C0C0",
    surface: "#1a0b15",
    surfaceMuted: "#120813",
    fgMuted: "#9CA3AF",
    muted: "#4B5563",
    primary: "#EF4444",
    primaryDark: "#DC2626",
    primaryText: "#FCA5A5",
    primaryStrong: "#B91C1C",
    primaryBorder: "#7F1D1D",
    primaryBg: "#1c0a0a",
    primaryTint: "#2d0f0f",
    secondary: "#F97316",
    secondaryDark: "#EA580C",
    secondaryText: "#FDBA74",
    secondaryTint: "#1c0d05",
    secondaryBorder: "#7c2d12",
    accent: "#C084FC",
    accentDark: "#A855F7",
    accentText: "#E9D5FF",
    accentStrong: "#7C3AED",
    accentTint: "#1e0a2e",
    accentBorder: "#4c1d95",
    success: "#34D399",
    successDark: "#10B981",
    successText: "#6EE7B7",
    successTint: "#022c22",
    successBorder: "#064e3b",
    danger: "#F87171",
    dangerDark: "#EF4444",
    dangerText: "#FECACA",
    dangerTint: "#1c0505",
    dangerBorder: "#7f1d1d",
    info: "#818CF8",
    infoDark: "#6366F1",
    infoText: "#C7D2FE",
    infoTint: "#0f0f2e",
    infoBorder: "#1e1b4b",
  },
};

// ---------------------------------------------------------------------------
// NativeWind CSS variable maps — applied to root View style
// ---------------------------------------------------------------------------
export const THEME_VARS: Record<ThemeName, ReturnType<typeof vars>> = {
  candy: vars({
    "--color-bg": THEME_COLORS.candy.bg,
    "--color-fg": THEME_COLORS.candy.fg,
    "--color-surface": THEME_COLORS.candy.surface,
    "--color-surface-muted": THEME_COLORS.candy.surfaceMuted,
    "--color-fg-muted": THEME_COLORS.candy.fgMuted,
    "--color-muted": THEME_COLORS.candy.muted,
    "--color-primary": THEME_COLORS.candy.primary,
    "--color-primary-dark": THEME_COLORS.candy.primaryDark,
    "--color-primary-text": THEME_COLORS.candy.primaryText,
    "--color-primary-strong": THEME_COLORS.candy.primaryStrong,
    "--color-primary-border": THEME_COLORS.candy.primaryBorder,
    "--color-primary-bg": THEME_COLORS.candy.primaryBg,
    "--color-primary-tint": THEME_COLORS.candy.primaryTint,
    "--color-secondary": THEME_COLORS.candy.secondary,
    "--color-secondary-dark": THEME_COLORS.candy.secondaryDark,
    "--color-secondary-text": THEME_COLORS.candy.secondaryText,
    "--color-secondary-tint": THEME_COLORS.candy.secondaryTint,
    "--color-secondary-border": THEME_COLORS.candy.secondaryBorder,
    "--color-accent": THEME_COLORS.candy.accent,
    "--color-accent-dark": THEME_COLORS.candy.accentDark,
    "--color-accent-text": THEME_COLORS.candy.accentText,
    "--color-accent-strong": THEME_COLORS.candy.accentStrong,
    "--color-accent-tint": THEME_COLORS.candy.accentTint,
    "--color-accent-border": THEME_COLORS.candy.accentBorder,
    "--color-success": THEME_COLORS.candy.success,
    "--color-success-dark": THEME_COLORS.candy.successDark,
    "--color-success-text": THEME_COLORS.candy.successText,
    "--color-success-tint": THEME_COLORS.candy.successTint,
    "--color-success-border": THEME_COLORS.candy.successBorder,
    "--color-danger": THEME_COLORS.candy.danger,
    "--color-danger-dark": THEME_COLORS.candy.dangerDark,
    "--color-danger-text": THEME_COLORS.candy.dangerText,
    "--color-danger-tint": THEME_COLORS.candy.dangerTint,
    "--color-danger-border": THEME_COLORS.candy.dangerBorder,
    "--color-info": THEME_COLORS.candy.info,
    "--color-info-dark": THEME_COLORS.candy.infoDark,
    "--color-info-text": THEME_COLORS.candy.infoText,
    "--color-info-tint": THEME_COLORS.candy.infoTint,
    "--color-info-border": THEME_COLORS.candy.infoBorder,
  }),
  ice: vars({
    "--color-bg": THEME_COLORS.ice.bg,
    "--color-fg": THEME_COLORS.ice.fg,
    "--color-surface": THEME_COLORS.ice.surface,
    "--color-surface-muted": THEME_COLORS.ice.surfaceMuted,
    "--color-fg-muted": THEME_COLORS.ice.fgMuted,
    "--color-muted": THEME_COLORS.ice.muted,
    "--color-primary": THEME_COLORS.ice.primary,
    "--color-primary-dark": THEME_COLORS.ice.primaryDark,
    "--color-primary-text": THEME_COLORS.ice.primaryText,
    "--color-primary-strong": THEME_COLORS.ice.primaryStrong,
    "--color-primary-border": THEME_COLORS.ice.primaryBorder,
    "--color-primary-bg": THEME_COLORS.ice.primaryBg,
    "--color-primary-tint": THEME_COLORS.ice.primaryTint,
    "--color-secondary": THEME_COLORS.ice.secondary,
    "--color-secondary-dark": THEME_COLORS.ice.secondaryDark,
    "--color-secondary-text": THEME_COLORS.ice.secondaryText,
    "--color-secondary-tint": THEME_COLORS.ice.secondaryTint,
    "--color-secondary-border": THEME_COLORS.ice.secondaryBorder,
    "--color-accent": THEME_COLORS.ice.accent,
    "--color-accent-dark": THEME_COLORS.ice.accentDark,
    "--color-accent-text": THEME_COLORS.ice.accentText,
    "--color-accent-strong": THEME_COLORS.ice.accentStrong,
    "--color-accent-tint": THEME_COLORS.ice.accentTint,
    "--color-accent-border": THEME_COLORS.ice.accentBorder,
    "--color-success": THEME_COLORS.ice.success,
    "--color-success-dark": THEME_COLORS.ice.successDark,
    "--color-success-text": THEME_COLORS.ice.successText,
    "--color-success-tint": THEME_COLORS.ice.successTint,
    "--color-success-border": THEME_COLORS.ice.successBorder,
    "--color-danger": THEME_COLORS.ice.danger,
    "--color-danger-dark": THEME_COLORS.ice.dangerDark,
    "--color-danger-text": THEME_COLORS.ice.dangerText,
    "--color-danger-tint": THEME_COLORS.ice.dangerTint,
    "--color-danger-border": THEME_COLORS.ice.dangerBorder,
    "--color-info": THEME_COLORS.ice.info,
    "--color-info-dark": THEME_COLORS.ice.infoDark,
    "--color-info-text": THEME_COLORS.ice.infoText,
    "--color-info-tint": THEME_COLORS.ice.infoTint,
    "--color-info-border": THEME_COLORS.ice.infoBorder,
  }),
  nightosphere: vars({
    "--color-bg": THEME_COLORS.nightosphere.bg,
    "--color-fg": THEME_COLORS.nightosphere.fg,
    "--color-surface": THEME_COLORS.nightosphere.surface,
    "--color-surface-muted": THEME_COLORS.nightosphere.surfaceMuted,
    "--color-fg-muted": THEME_COLORS.nightosphere.fgMuted,
    "--color-muted": THEME_COLORS.nightosphere.muted,
    "--color-primary": THEME_COLORS.nightosphere.primary,
    "--color-primary-dark": THEME_COLORS.nightosphere.primaryDark,
    "--color-primary-text": THEME_COLORS.nightosphere.primaryText,
    "--color-primary-strong": THEME_COLORS.nightosphere.primaryStrong,
    "--color-primary-border": THEME_COLORS.nightosphere.primaryBorder,
    "--color-primary-bg": THEME_COLORS.nightosphere.primaryBg,
    "--color-primary-tint": THEME_COLORS.nightosphere.primaryTint,
    "--color-secondary": THEME_COLORS.nightosphere.secondary,
    "--color-secondary-dark": THEME_COLORS.nightosphere.secondaryDark,
    "--color-secondary-text": THEME_COLORS.nightosphere.secondaryText,
    "--color-secondary-tint": THEME_COLORS.nightosphere.secondaryTint,
    "--color-secondary-border": THEME_COLORS.nightosphere.secondaryBorder,
    "--color-accent": THEME_COLORS.nightosphere.accent,
    "--color-accent-dark": THEME_COLORS.nightosphere.accentDark,
    "--color-accent-text": THEME_COLORS.nightosphere.accentText,
    "--color-accent-strong": THEME_COLORS.nightosphere.accentStrong,
    "--color-accent-tint": THEME_COLORS.nightosphere.accentTint,
    "--color-accent-border": THEME_COLORS.nightosphere.accentBorder,
    "--color-success": THEME_COLORS.nightosphere.success,
    "--color-success-dark": THEME_COLORS.nightosphere.successDark,
    "--color-success-text": THEME_COLORS.nightosphere.successText,
    "--color-success-tint": THEME_COLORS.nightosphere.successTint,
    "--color-success-border": THEME_COLORS.nightosphere.successBorder,
    "--color-danger": THEME_COLORS.nightosphere.danger,
    "--color-danger-dark": THEME_COLORS.nightosphere.dangerDark,
    "--color-danger-text": THEME_COLORS.nightosphere.dangerText,
    "--color-danger-tint": THEME_COLORS.nightosphere.dangerTint,
    "--color-danger-border": THEME_COLORS.nightosphere.dangerBorder,
    "--color-info": THEME_COLORS.nightosphere.info,
    "--color-info-dark": THEME_COLORS.nightosphere.infoDark,
    "--color-info-text": THEME_COLORS.nightosphere.infoText,
    "--color-info-tint": THEME_COLORS.nightosphere.infoTint,
    "--color-info-border": THEME_COLORS.nightosphere.infoBorder,
  }),
};
