// Writes the token files that mobile and web consume from packages/theme.
// Run `npm run build -w @adventure-time/theme` after changing a token;
// `npm run check -w @adventure-time/theme` fails when an output is stale.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  CONTROL,
  getLineHeightPx,
  getThemeColorScheme,
  getThemeCssVariables,
  getThemeEffectCssVariables,
  RADIUS,
  SPACE,
  THEME_COLORS,
  THEME_CSS_VARIABLE_NAMES,
  THEME_EFFECT_CSS_VARIABLE_NAMES,
  THEME_NAMES,
  TYPE,
  type ThemeName,
  type TypeRole,
} from "../src/index.ts";

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoDir = resolve(packageDir, "../..");

const HEADER = "Generated by packages/theme/scripts/generate.ts. Do not edit.";

const CONTROL_KEYS: Record<keyof typeof CONTROL, string> = {
  lg: "control-lg",
  md: "control-md",
  sm: "control-sm",
  iconButton: "icon-button",
  input: "input",
  header: "header",
  tabBar: "tab-bar",
};

function declarations(variables: Record<string, string>, indent = "  ") {
  return Object.entries(variables)
    .map(([name, value]) => `${indent}${name}: ${value};`)
    .join("\n");
}

function themeVariables(themeName: ThemeName) {
  return {
    ...getThemeCssVariables(themeName),
    ...getThemeEffectCssVariables(themeName),
  };
}

function scaleVariables() {
  const variables: Record<string, string> = {};

  for (const [name, value] of Object.entries(RADIUS)) {
    variables[`--radius-${name}`] = `${value}px`;
  }
  for (const [name, value] of Object.entries(SPACE)) {
    variables[`--space-${name}`] = `${value}px`;
  }
  for (const role of Object.keys(TYPE) as TypeRole[]) {
    variables[`--text-${role}`] = `${TYPE[role].size}px`;
    variables[`--leading-${role}`] = `${getLineHeightPx(role)}px`;
  }
  for (const [name, value] of Object.entries(CONTROL)) {
    variables[`--${CONTROL_KEYS[name as keyof typeof CONTROL]}`] = `${value}px`;
  }

  return variables;
}

function mobileGlobalCss() {
  return `/* ${HEADER}
 * :root carries the default (candy) theme; ice and nightosphere are applied
 * at runtime through THEME_VARS in apps/mobile/src/theme/themes.ts. */
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
${declarations(themeVariables("candy"))}
}
`;
}

function webThemeCss() {
  const blocks = THEME_NAMES.map((themeName) => {
    const selector =
      themeName === "candy"
        ? `:root,\n:root[data-theme="candy"]`
        : `:root[data-theme="${themeName}"]`;

    return `${selector} {
  color-scheme: ${getThemeColorScheme(themeName)};
${declarations(themeVariables(themeName))}
}`;
  });

  const swatches = THEME_NAMES.map(
    (themeName) => `.theme-option-${themeName} {
  --swatch: ${THEME_COLORS[themeName].primary};
}`,
  );

  return `/* ${HEADER} */

${blocks.join("\n\n")}

:root {
${declarations(scaleVariables())}
}

${swatches.join("\n\n")}
`;
}

function tailwindTokens() {
  const colors = Object.fromEntries([
    ...Object.entries(THEME_CSS_VARIABLE_NAMES),
    ...Object.entries(THEME_EFFECT_CSS_VARIABLE_NAMES),
  ].map(([name, variable]) => [name, `var(${variable})`]));

  const borderRadius = Object.fromEntries(
    Object.entries(RADIUS).map(([name, value]) => [`ds-${name}`, `${value}px`]),
  );

  const spacing = {
    ...Object.fromEntries(
      Object.entries(SPACE).map(([name, value]) => [`ds-${name}`, `${value}px`]),
    ),
    ...Object.fromEntries(
      Object.entries(CONTROL).map(([name, value]) => [
        CONTROL_KEYS[name as keyof typeof CONTROL],
        `${value}px`,
      ]),
    ),
  };

  const fontSize = Object.fromEntries(
    (Object.keys(TYPE) as TypeRole[]).map((role) => [
      `ds-${role}`,
      [`${TYPE[role].size}px`, { lineHeight: `${getLineHeightPx(role)}px` }],
    ]),
  );

  return `// ${HEADER}
module.exports = ${JSON.stringify({ colors, borderRadius, spacing, fontSize }, null, 2)};
`;
}

const outputs: Record<string, string> = {
  "apps/mobile/global.css": mobileGlobalCss(),
  "apps/web/src/theme/theme.css": webThemeCss(),
  "packages/theme/generated/tailwind-tokens.cjs": tailwindTokens(),
};

const check = process.argv.includes("--check");
const stale: string[] = [];

for (const [path, content] of Object.entries(outputs)) {
  const target = resolve(repoDir, path);
  let current: string | null = null;

  try {
    current = readFileSync(target, "utf8");
  } catch {
    current = null;
  }

  if (current === content) {
    continue;
  }

  if (check) {
    stale.push(relative(repoDir, target));
  } else {
    writeFileSync(target, content);
    console.log(`wrote ${relative(repoDir, target)}`);
  }
}

if (stale.length > 0) {
  console.error(
    `Stale generated theme files:\n${stale.map((path) => `  ${path}`).join("\n")}\nRun npm run build -w @adventure-time/theme.`,
  );
  process.exit(1);
}
